# Generated by Django 3.2.12 on 2024-05-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
