# Generated by Django 3.2.12 on 2024-05-09 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_answer_question_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='sydney_correct_count_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
