# Generated by Django 3.2.12 on 2024-05-09 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_summary_sydney_correct_count_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summary',
            old_name='sydney_correct_count_percentage',
            new_name='sydney_average_score',
        ),
    ]
