# Generated by Django 3.2.12 on 2024-05-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0004_rename_sydney_correct_count_percentage_summary_sydney_average_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='sydney_average_score',
        ),
        migrations.AddField(
            model_name='summary',
            name='student_total_assessed',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
