# Generated by Django 3.2.12 on 2024-05-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0007_auto_20240509_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='correct_answer_percentage_per_class',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='summary',
            name='total_area_assessed_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
