# Generated by Django 3.2.12 on 2024-05-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0009_summary_average_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='school_percentile',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='summary',
            name='category_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='summary',
            name='correct_answer',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='summary',
            name='correct_answer_id',
            field=models.IntegerField(default=0),
        ),
    ]
