# Generated by Django 3.2.12 on 2024-05-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0010_auto_20240509_0641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='assessment_area',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='award',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='sydney_percentile',
        ),
        migrations.AlterField(
            model_name='summary',
            name='sydney_participant',
            field=models.IntegerField(default=0),
        ),
    ]
