# Generated by Django 3.2.12 on 2024-05-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0011_auto_20240509_0659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question_number',
        ),
        migrations.AlterField(
            model_name='answer',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='assessmentarea',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='award',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='class',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='school',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
