# Generated by Django 3.2.12 on 2024-05-09 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0012_auto_20240509_0717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summary',
            old_name='school',
            new_name='school_id',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='average_score',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='school_percentile',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='student',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='student_area_assessed_score',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='student_total_assessed',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='sydney_average_score',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='total_area_assessed_score',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='year_level_name',
        ),
        migrations.AddField(
            model_name='summary',
            name='Assessment_Area_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='school_app.assessmentarea'),
        ),
        migrations.AddField(
            model_name='summary',
            name='Award_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='school_app.award'),
        ),
        migrations.AddField(
            model_name='summary',
            name='Class_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='school_app.class'),
        ),
        migrations.AddField(
            model_name='summary',
            name='student_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='school_app.student'),
        ),
        migrations.AddField(
            model_name='summary',
            name='subject_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='school_app.subject'),
        ),
        migrations.AddField(
            model_name='summary',
            name='sydney_percentile',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='summary',
            name='participant',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='summary',
            name='student_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
