# Generated by Django 3.2.12 on 2024-05-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0013_auto_20240509_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
